name: ShellSpec Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ShellSpec
        run: |
          curl -fsSL https://git.io/shellspec | sh -s -- --yes
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run ShellSpec
        run: shellspec
